name: 'Git commit'
description: 'Commit changed file to destination repository'
inputs:
  src:
    description: 'Source file from the origin directory. Can be a file, glob (`*.json`) or folder'
    required: true
  branch:
    description: 'Destination branch'
    required: true
  dst:
    description: 'Directory to push the source to'
    required: true
  user_name:
    description: 'GitHub username for the commit. Defaults to GITHUB_ACTOR'
    required: false
  user_email:
    description: 'Email for the git commit. Defaults to commit author email'
    required: false
  repository:
    description: 'Destination repository, if not provided it will commit back to the same repo'
    required: false
  commit_message:
    description: 'A custom message for the commit'
    required: false
  pr_create:
    description: 'Create pull request automatically if changes are successfully commited'
    required: false
  pr_title:
    description: 'Pull request title'
    required: false
  pr_description:
    description: 'Pull request description'
    required: false
  pr_base:
    description: 'Create pull request again specific base. Defaults to master branch'
    required: false
    default: 'master'
  labels:
    description: 'Mark PR with specific labels. Multiple labels separate with space'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.src }}
    - ${{ inputs.branch }}
    - ${{ inputs.dst }}
    - ${{ inputs.user-name }}
    - ${{ inputs.user-email }}
    - ${{ inputs.repository }}
    - ${{ inputs.commit-message }}
    - ${{ inputs.pr-create }}
    - ${{ inputs.pr-title }}
    - ${{ inputs.pr-description }}
    - ${{ inputs.pr-base }}
    - ${{ inputs.labels }}
branding:
  icon: 'git-commit'
  color: 'green'