name: Git commit

on: [pull_request]

env:
  sha: $GITHUB_SHA

jobs:
  git-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Mark test file
        run: |
          echo $GITHUB_SHA > test02.md
          mkdir -p docs/1/2
          echo $GITHUB_SHA > docs/test01.md
          echo $GITHUB_SHA > docs/test02.md
          mkdir docs-test-folder
          echo $GITHUB_SHA > docs-test-folder/test01.md
          echo $GITHUB_SHA > git-commit/examples/1/openapi.gen.yaml
          echo $GITHUB_SHA > git-commit/examples/2/openapi.gen.yaml

      - name: Overwrite
        uses: ./git-commit
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          src: 'git-commit/**/*.gen.yaml'
          overwrite: true
          branch: 'git-commit-glob'
          pr_create: true
          pr_base: 'master'
          pr_title: "Overwrite: ${{ github.repository }}"

      - name: Push specific file
        uses: ./git-commit
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          src: 'test02.md'
          branch: 'git-commit-file'
          pr_create: true
          pr_base: 'master'
          pr_title: "Push specific file: ${{ github.repository }}"

      - name: Push specific folder
        uses: ./git-commit
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          src: 'docs-test-folder/'
          dst: 'docs-test-folder/'
          branch: 'git-commit-folder'
          pr_create: true
          pr_base: 'master'

      - name: Push multiple files
        uses: ./git-commit
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          src: 'docs/*.md'
          dst: 'docs/'
          branch: 'git-commit-multiple-files'
          pr_create: true
          pr_base: 'master'
