name: Git commit

on: [pull_request]

env:
  sha: $GITHUB_SHA

jobs:
  git-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Mark test file
        run: |
          echo $GITHUB_SHA > test02.md
          mkdir docs
          echo $GITHUB_SHA > docs/test01.md
          echo $GITHUB_SHA > docs/test02.md
          mkdir docs-test-folder
          echo $GITHUB_SHA > docs-test-folder/test01.md
          echo $(pwd)

      - name: Push specific file
        uses: ./git-commit
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          src: 'test02.md'
          dst_branch: 'git-commit-file'
          user_email: 'lj@horizon.io'
          pr_create: 'true'
          pr_base: 'master'
          pr_title: "Push specific file: ${{ github.repository }}"

      - name: Push specific folder
        uses: ./git-commit
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          src: 'docs-test-folder/'
          dst: 'docs-test-folder/'
          dst_branch: 'git-commit-folder'
          user_email: 'lj@horizon.io'
          pr_create: 'true'
          pr_base: 'master'

      - name: Push multiple files
        uses: ./git-commit
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          src: 'docs/*.md'
          dst: 'docs/'
          dst_branch: 'git-commit-multiple-files'
          user_email: 'lj@horizon.io'
          pr_create: 'true'
          pr_base: 'master'
