name: Git commit

on: [pull_request]

env:
  sha: $GITHUB_SHA

jobs:
  git-copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Mark test file
        run: |
          echo $GITHUB_SHA >> git-commit/examples/1/example.gen.yaml
          echo $GITHUB_SHA >> git-commit/examples/2/example.gen.yaml
          rm git-commit/examples/3/deprecated.json

      - name: Mark test file
        run: |
          echo "### Git commit action! :rocket:" >> $GITHUB_STEP_SUMMARY

      - name: Changed files
        uses: ./git-commit
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: 'git-commit/examples/**/*.gen.yaml'
          branch: 'git-commit'
          pr_title: "[GIT-COMMIT]: Use glob pattern ${{ github.repository }}"
          pr_create: true
          pr_base: 'master'

      - name: Removed file
        uses: ./git-commit
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: 'git-commit/examples/3/deprecated.json git-commit/examples/4/deprecated.json'
          branch: 'git-commit'
          pr_title: "[GIT-COMMIT]: Push back deleted file ${{ github.repository }}"
          pr_create: true
          pr_base: 'master'

